// Generated by FlutterFire CLI (manual fallback).
// Please do not commit API keys to public repositories.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: 'AIzaSyABUe_pjtc01mcHHEGXSLnNDTi6neVRGHI',
        authDomain: 'visual-app-2026.firebaseapp.com',
        projectId: 'visual-app-2026',
        storageBucket: 'visual-app-2026.firebasestorage.app',
        messagingSenderId: '441635280173',
        appId: '1:441635280173:web:e3f7f0353c16c51d806fa4',
        measurementId: 'G-EW261LW6HW',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: 'AIzaSyBLcZ96JHpxy1MQ4j-RKz0Y-RyftkiLAks',
          appId: '1:441635280173:android:4380c44c1ea35804806fa4',
          messagingSenderId: '441635280173',
          projectId: 'visual-app-2026',
          storageBucket: 'visual-app-2026.firebasestorage.app',
        );
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: 'AIzaSyBFXqjbz6HdF08VI_hn7mG16fMA6afr9gA',
          appId: '1:441635280173:ios:336c852bef131158806fa4',
          messagingSenderId: '441635280173',
          projectId: 'visual-app-2026',
          storageBucket: 'visual-app-2026.firebasestorage.app',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
